name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # mejor entre comillas
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install fastapi "uvicorn[standard]" pytest

      - name: Smoke index + run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.index_folder --path ./root   --ext .py,.md,.txt --mode fresh
          python -m scripts.index_folder --path ./rag    --ext .py,.md,.txt --mode append
          python -m scripts.index_folder --path ./memory --ext .py,.md,.txt --mode append
          pytest -q
